### ISSUE TITLE
RFE: XFL API compatibility.

### ISSUE THREAD

**Issue by timflannagan** [Daniel-Pivonka/timbot#55]
Support querying an existing pro sports API for XFL scheduling.

**Comment by Daniel-Pivonka** [comment]
I hate the XFL

**Comment by Daniel-Pivonka** [comment]
i have request access the the xfl api. ill update if i get access

**Comment by Daniel-Pivonka** [comment]
no update from the xfl :-1:

**Comment by timflannagan** [comment]
@Daniel-Pivonka ping - any updates on this mission-critical issue?

**Comment by timflannagan** [comment]
Any updates on this?

**Comment by Daniel-Pivonka** [comment]
Closing Issue given the circumstances https://www.cbssports.com/xfl/news/xfl-suspends-operations-and-lays-off-employees-currently-has-no-plans-to-return-in-2021-per-report/

**Comment by timflannagan** [comment]
@rafaelquint is this something you have the capacity to take on?
