### ISSUE TITLE
Add webopoly win incrementing functionality to timbot

### ISSUE THREAD

**Issue by nathan-weinberg** [Daniel-Pivonka/timbot#72]
Need to add a system that allows users, with a consensus, to increment a user's Webopoly win count using the db function introduced in #71

**Comment by nathan-weinberg** [comment]
@Daniel-Pivonka now that #71 has been merged this is maximum priority

**Comment by nathan-weinberg** [comment]
@timflannagan1 Not sure Dan can handle this, better help him out

**Comment by timflannagan** [comment]
I trust @Daniel-Pivonka to handle this critical issue, by himself.

**Comment by nathan-weinberg** [comment]
Dan's incompetence can no longer be tolerated
